# Generated by Django 2.2.5 on 2020-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=50)),
                ('P_ig', models.CharField(max_length=50)),
                ('P_say', models.CharField(max_length=200)),
                ('P_result', models.CharField(max_length=50)),
                ('P_time', models.CharField(max_length=50)),
            ],
        ),
    ]
